# Use as docker-compose --env-file .env up
version: "3.8"
services:
  redis_db:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    command: /scripts/run_backend_dev.sh
    volumes:
      - ./backend:/code/backend
      - ./docs:/code/docs
      - ./migrations:/code/migrations
      - ./tasks:/code/tasks
      - ./tests:/code/tests
      - ./plugins:/code/plugins
      - ./requirements/backend.txt:/code/requirements.txt
      - ./scripts:/scripts
      - ./mkdocs.yml:/code/mkdocs.yml
      - ./xvnc_passwd:/code/xvnc_passwd
    env_file:
      - .env
    depends_on:
      - redis_db
    ports:
      - "5000:5000"
      - "5800-5899:5800-5899"
  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.frontend
    volumes:
      - ./scripts:/scripts
      - ./frontend:/frontend
      - /frontend/node_modules/
    env_file:
      - .env
    ports:
      - "3000:3000"
    entrypoint: "/bin/bash"
    command: "/scripts/run_frontend_dev.sh"

