FROM node:14.13.1-buster-slim


RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 python3-pip

RUN mkdir /frontend
COPY ./frontend /frontend
COPY ./scripts /scripts
WORKDIR /frontend

RUN npm install

RUN sed -i 's/\r$//' /scripts/run_frontend.sh  && chmod +x /scripts/run_frontend.sh

CMD ["/scripts/run_frontend.sh"]
